# Generated by Django 4.2.6 on 2024-04-23 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estilos',
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tecnicas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('fotoPerfil', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, serialize=False, to='publicart.usuario', verbose_name='Usuairos')),
                ('likes', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=False)),
                ('precio', models.PositiveIntegerField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Publicación')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.estilo', verbose_name='Estilos')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.tecnica', verbose_name='Tecnicas')),
            ],
            options={
                'verbose_name_plural': 'Obras',
            },
        )
    ]
