# Generated by Django 4.2.6 on 2024-04-23 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fotoPerfil',
            new_name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='usuario',
        ),
        migrations.AddField(
            model_name='obra',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Publicación')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.obra', verbose_name='Obras')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.usuario', verbose_name='Usuarios')),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
