# Generated by Django 4.2.6 on 2024-04-23 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0003_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilo',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.CharField(max_length=255, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='disponible',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.CharField(max_length=200, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=9, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.CharField(max_length=255, verbose_name='Foto Perfil'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.obra', verbose_name='Obras')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.usuario', verbose_name='Usuarios')),
            ],
        ),
    ]
