# Generated by Django 4.2.6 on 2024-04-23 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0004_alter_estilo_descripcion_alter_foto_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.obra', verbose_name='Obras')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.usuario', verbose_name='Usuarios')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
