# Generated by Django 4.2.6 on 2024-04-23 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0006_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fechas'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=500, verbose_name='Textos'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fechas Compra'),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripciones'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.CharField(max_length=255, verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripciones'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='disponible',
            field=models.BooleanField(default=False, verbose_name='Descripciones'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precios'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fechas Publicación'),
        ),
        migrations.AlterField(
            model_name='tecnica',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripciones'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.CharField(max_length=200, verbose_name='Biografías'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Direcciones'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.CharField(max_length=255, verbose_name='Fots Perfil'),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500, verbose_name='Contenidos')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fechas')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.usuario', verbose_name='Autores')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicart.chat', verbose_name='Chats')),
            ],
            options={
                'verbose_name_plural': 'Conversaciones',
            },
        ),
    ]
