# Generated by Django 4.2.6 on 2024-05-13 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0008_obra_usuario_alter_obra_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='disponible',
            field=models.BooleanField(default=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
