# Generated by Django 4.2.6 on 2024-05-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0009_alter_foto_foto_alter_obra_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='img/fotos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='img/usu', verbose_name='Foto de perfil'),
        ),
    ]
