# Generated by Django 4.2.6 on 2024-05-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0010_alter_foto_foto_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='publicart.usuario', verbose_name='Seguido')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidos', to='publicart.usuario', verbose_name='Seguidor')),
            ],
        ),
    ]
