# Generated by Django 4.2.6 on 2024-05-29 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicart', '0011_remove_obra_usuario_seguimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'verbose_name_plural': 'Seguimientos'},
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seguido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL, verbose_name='Seguido'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seguidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidos', to=settings.AUTH_USER_MODEL, verbose_name='Seguidor'),
        ),
        migrations.AlterUniqueTogether(
            name='seguimiento',
            unique_together={('seguidor', 'seguido')},
        ),
    ]
