# Generated by Django 4.2.6 on 2024-06-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0014_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='obra',
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='publicart.publicacion', verbose_name='Publicación'),
        ),
    ]
