# Generated by Django 4.2.6 on 2024-06-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0015_remove_comentario_obra_comentario_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='likes',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='num_seguidores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='num_seguidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicart.usuario', verbose_name='Usuario'),
        ),
    ]
