# Generated by Django 4.2.6 on 2024-06-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0017_chat_leido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='leido',
        ),
        migrations.AddField(
            model_name='conversacion',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
    ]
