# Generated by Django 4.2.6 on 2024-06-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicart', '0018_remove_chat_leido_conversacion_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicart.chat', verbose_name='Chats'),
        ),
    ]
